# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.vonway.cn
date_format: "ordinal"
title: vonway
subtitle: "不吃羊的小灰灰"
description: "vonway's blog"
keywords: vonway
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: vonway
organization: VVV, Inc.
organization_url: https://www.vonway.cn
location: Shanghai, China
email: haisayu@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: home

  -
    href: /categories/
    label: categories

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: links

  -
    href: /about/
    label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: vonway
zhihu_username: 冯可烦

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: vonway
# disqus_username: 
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-86275366-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Linux, Database]
skill_mobile_app_keywords: [Android, iOS]
skill_windows_keywords: [C#]
github: [metadata]
